replicaCount: 1

# image.repository and image.tag are overwritten by Jenkins (see /Jenkinsfile).
# Before the first pipeline run, set repository to: terraform output -raw ecr_repository_url
image:
  repository: 815593910208.dkr.ecr.eu-north-1.amazonaws.com/goit-devops-hw-ecr
  tag: "manual-20260425-140350"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

config:
  DJANGO_SETTINGS_MODULE: mysite.settings

hpa:
  enabled: true
